name: guiademoteisgo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  fpdart: ^1.1.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/png/

  fonts:
    - family: CronosPro
      fonts:
        - asset: assets/fonts/Cronos-Pro.ttf
