name: guiademoteisgo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  fpdart: ^1.1.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/png/icon.png"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/png/icon.png"

flutter_native_splash:
  color: "#D11521"
  image: assets/png/icon_splash.png

  android_12:
    image: assets/png/icon_splash.png
    icon_background_color: "#D11521"

  web: false
# To generate icons:
#  dart run flutter_launcher_icons:main
flutter:
  uses-material-design: true
  assets:
    - assets/png/
