name: guiademoteisgo
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  fpdart: ^1.1.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  go_router: ^14.7.2
  http: ^1.3.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3

plutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon.png"
#   adaptive_icon_background: "#F44336"
#   adaptive_icon_foreground: "assets/images/icon.png"
# To generate icons:
#  dart run flutter_launcher_icons:main
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
